// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpmweyfstejwjesvgguh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbXdleWZzdGVqd2plc3ZnZ3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDk2NDksImV4cCI6MjA2MzEyNTY0OX0.DX5LnVeXlJcCMg-kNwW6Y5Fm5_3cZUZHctJ88-jIoy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);